#!/bin/bash

#variables
mailaddr_to=YOUREMAIL@DOMAIN.TLD
mailaddr_from=EMAIL@YOURDOMAIN.TLD
logpath=/var/log/proftpd/
email=yes

#cleaning work environment
rm -f /tmp/proftpd_daily_log*

#collecting daily log
cat $logpath/proftpd.log | grep $(date -d "yesterday" '+%Y-%m-%d') >> /tmp/proftpd_daily_log.tmp
cat $logpath/proftpd.log.1 | grep $(date -d "yesterday" '+%Y-%m-%d') >> /tmp/proftpd_daily_log.tmp
zcat $logpath/proftpd.log.*.gz | grep $(date -d "yesterday" '+%Y-%m-%d') >> /tmp/proftpd_daily_log.tmp

#sorting log entries
cat /tmp/proftpd_daily_log.tmp | sort -M -k 2 >> /tmp/proftpd_daily_log

##preparing report
echo -e "LogReport Proftpd $(date -d "yesterday" '+%d.%m.%Y')\n" >> /tmp/proftpd_daily_log.1
echo -e "---------------------- Proftpd -------------------------\n" >> /tmp/proftpd_daily_log.1
#proftpd service
service proftpd status >> /tmp/proftpd_daily_log.1

cat /tmp/proftpd_daily_log | grep STARTUP >> /tmp/proftpd_daily_log.server
cat /tmp/proftpd_daily_log | grep SHUTDOWN >> /tmp/proftpd_daily_log.server
cat /tmp/proftpd_daily_log | grep killed >> /tmp/proftpd_daily_log.server

cat /tmp/proftpd_daily_log.server | sort -M -k 2 >> /tmp/proftpd_daily_log.1

echo -e "------------------------ User ---------------------------\n" >> /tmp/proftpd_daily_log.1
cat /tmp/proftpd_daily_log | grep USER >> /tmp/proftpd_daily_log.1

echo -e "---------------------- User End -------------------------" >> /tmp/proftpd_daily_log.1
echo -e "-------------------- Proftpd End ------------------------\n" >> /tmp/proftpd_daily_log.1

#pushing to logfile
cat /tmp/proftpd_daily_log.1 >> /var/log/proftpd/proftpd_report.log

#mail daily reports
if [ $email == yes ]; then
		#file is not empty
		echo -e "To: $mailaddr_to" > /tmp/proftpd_daily_log.report
		echo -e "From: $mailaddr_from" >> /tmp/proftpd_daily_log.report
		echo -e "Subject: LogReport Proftpd $(date -d "yesterday" '+%d.%m.%Y')" >> /tmp/proftpd_daily_log.report
		echo "" >> /tmp/proftpd_daily_log.report
		cat /tmp/proftpd_daily_log.1 >> /tmp/proftpd_daily_log.report
		su proftpd -s /bin/sh -c 'cat /tmp/proftpd_daily_log.report | /usr/sbin/sendmail -t'
fi

#removing tmp
rm -f /tmp/proftpd_daily_log*
